routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect( route('login') );
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/store', 'AdminController@store')->name('store');
        Route::get('/edit/{admin}', 'AdminController@edit')->name('edit');
        Route::get('/folder/change/{admin}/{folder}', 'AdminController@change')->name('change');
        Route::post('/update/{admin}', 'AdminController@update')->name('update');
        Route::get('/delete/{admin}', 'AdminController@delete')->name('delete');
    });
    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/store', 'CustomerController@store')->name('store');
        Route::get('/edit/{customer}', 'CustomerController@edit')->name('edit');
        Route::get('/folder/change/{customer}/{folder}', 'CustomerController@change')->name('change');
        Route::post('/update/{customer}', 'CustomerController@update')->name('update');
        Route::get('/delete/{customer}', 'CustomerController@delete')->name('delete');
        Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
            Route::post('/store/{customer}', 'CustomerCourseController@store')->name('store');
            Route::post('/update/{course}', 'CustomerCourseController@update')->name('update');
            Route::get('/delete/{course}', 'CustomerCourseController@delete')->name('delete');
        });
    });
    Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
        Route::get('/', 'CourseController@index')->name('index');
        Route::get('/create', 'CourseController@create')->name('create');
        Route::post('/store', 'CourseController@store')->name('store');
        Route::get('/edit/{course}', 'CourseController@edit')->name('edit');
        Route::get('/folder/change/{course}/{folder}', 'CourseController@change')->name('change');
        Route::post('/update/{course}', 'CourseController@update')->name('update');
        Route::get('/delete/{course}', 'CourseController@delete')->name('delete');
    });
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
    Route::group(['prefix' => 'folder', 'as' => 'folder.'], function () {
        Route::post('/store', 'FolderController@store')->name('store');
        Route::post('/update/{folder}', 'FolderController@update')->name('update');
        Route::get('/delete/{folder}', 'FolderController@delete')->name('delete');
    });
    Route::group(['prefix' => 'video', 'as' => 'video.'], function () {
        Route::post('/store', 'VideoController@store')->name('store');
        Route::post('/update/{video}', 'VideoController@update')->name('update');
        Route::get('/delete/{video}', 'VideoController@delete')->name('delete');
    });
    Route::group(['prefix' => 'document', 'as' => 'document.'], function () {
        Route::post('/store', 'DocumentController@store')->name('store');
        Route::post('/update/{document}', 'DocumentController@update')->name('update');
        Route::get('/change/{document}', 'DocumentController@change')->name('change');
        Route::get('/delete/{document}', 'DocumentController@delete')->name('delete');
    });
});

Route::group(['prefix' => 'customer'], function () {
    Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'CustomerAuth\LoginController@login');
    Route::get('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'CustomerAuth\RegisterController@register');

    Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => 'customer', 'namespace' => 'Customer'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
});
Route::get('/rodar-funcao', function(){
    getDocuments();
});

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    //
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Folder;
use App\Http\Controllers\Controller;

class ContentController extends Controller
{
    public function index()
    {
        $folders = Folder::whereNull('folder_id')->get();
        return view('admin.pages.content.index')
            ->with('folders', $folders);
    }

    public function show(Folder $folder)
    {
        $folderMaster = Folder::find($folder->folder_id);
        $isMaster = $folderMaster && $folderMaster->folder_id == null;
        return view('admin.pages.content.show')
        ->with('isMaster', $isMaster)
        ->with('folder', $folder);
    }
}

app/Http/Controllers/Customer/ContentController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Folder;

class ContentController extends Controller
{
    public function index()
    {
        $customer = auth()->guard('customer')->user();
        $courseId = $customer->courses()->whereDate('date', '>=', date("Y-m-d"))->pluck('courses.id')->toArray();
        $folders = Folder::join('permission_folders', 'permission_folders.folder_id', '=', 'folders.id')
            ->whereIn('course_id', $courseId)
            ->whereNull('folders.folder_id')
            ->select('folders.*')
            ->orderby('name', 'asc')
            ->get();
        return view('customer.pages.content.index')
            ->with('folders', $folders);
    }

    public function show(Folder $folder)
    {
        $customer = auth()->guard('customer')->user();
        $courseId = $customer->courses()->whereDate('date', '>=', date("Y-m-d"))->pluck('courses.id')->toArray();
        $subfolders = $folder
            ->join('permission_folders', 'permission_folders.folder_id', '=', 'folders.id')
            ->whereIn('course_id', $courseId)
            ->where('folders.folder_id', $folder->id)
            ->select('folders.*')
            ->orderby('name', 'asc')
            ->get();
        return view('customer.pages.content.show')
            ->with('folder', $folder)
            ->with('subfolders', $subfolders);
    }
}

resources/views/admin/pages/content/index.blade.php
@extends('admin.templates.default')

@section('title', 'Dashboard')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Conteúdo</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 ">
                    <button class="btn btn-primary-ieaga btn-sm float-right btn-content" id="btnAddFolder"><i
                            class="far fa-folder"></i> Adicionar Pasta</button>

                </div>
            </div>
            <h5 class="mb-2">Pastas</h5>

            <div class="row">
                @forelse($folders as $folder)
                <div class="col-sm-3">
                    @component('admin.components.folder',['folder' => $folder])
                    @endcomponent

                </div>
                @empty
                <div class="col">
                    <p>Nenhuma pasta encontrada</p>
                </div>
                @endforelse
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection
@section('scripts')
<script type="text/javascript">
$('#btnAddFolder').on('click', function() {
    $('#modalAddFolder').modal('show');
});

</script>
@endsection
@section('modals')
<div class="modal fade" id="modalAddFolder">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Adicionar Pasta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('admin.folder.store')}}" method="post">
                {{csrf_field()}}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="input-name-folder">Nome</label>
                                <input type="text" class="form-control" name="name" id="input-name-folder" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection