routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect( route('login') );
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/store', 'AdminController@store')->name('store');
        Route::get('/edit/{admin}', 'AdminController@edit')->name('edit');
        Route::get('/folder/change/{admin}/{folder}', 'AdminController@change')->name('change');
        Route::post('/update/{admin}', 'AdminController@update')->name('update');
        Route::get('/delete/{admin}', 'AdminController@delete')->name('delete');
    });
    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/store', 'CustomerController@store')->name('store');
        Route::get('/edit/{customer}', 'CustomerController@edit')->name('edit');
        Route::get('/folder/change/{customer}/{folder}', 'CustomerController@change')->name('change');
        Route::post('/update/{customer}', 'CustomerController@update')->name('update');
        Route::get('/delete/{customer}', 'CustomerController@delete')->name('delete');
        Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
            Route::post('/store/{customer}', 'CustomerCourseController@store')->name('store');
            Route::post('/update/{course}', 'CustomerCourseController@update')->name('update');
            Route::get('/delete/{course}', 'CustomerCourseController@delete')->name('delete');
        });
    });
    Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
        Route::get('/', 'CourseController@index')->name('index');
        Route::get('/create', 'CourseController@create')->name('create');
        Route::post('/store', 'CourseController@store')->name('store');
        Route::get('/edit/{course}', 'CourseController@edit')->name('edit');
        Route::get('/folder/change/{course}/{folder}', 'CourseController@change')->name('change');
        Route::post('/update/{course}', 'CourseController@update')->name('update');
        Route::get('/delete/{course}', 'CourseController@delete')->name('delete');
    });
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
    Route::group(['prefix' => 'folder', 'as' => 'folder.'], function () {
        Route::post('/store', 'FolderController@store')->name('store');
        Route::post('/update/{folder}', 'FolderController@update')->name('update');
        Route::get('/delete/{folder}', 'FolderController@delete')->name('delete');
    });
    Route::group(['prefix' => 'video', 'as' => 'video.'], function () {
        Route::post('/store', 'VideoController@store')->name('store');
        Route::post('/update/{video}', 'VideoController@update')->name('update');
        Route::get('/delete/{video}', 'VideoController@delete')->name('delete');
    });
    Route::group(['prefix' => 'document', 'as' => 'document.'], function () {
        Route::post('/store', 'DocumentController@store')->name('store');
        Route::post('/update/{document}', 'DocumentController@update')->name('update');
        Route::get('/change/{document}', 'DocumentController@change')->name('change');
        Route::get('/delete/{document}', 'DocumentController@delete')->name('delete');
    });
});

Route::group(['prefix' => 'customer'], function () {
    Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'CustomerAuth\LoginController@login');
    Route::get('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'CustomerAuth\RegisterController@register');

    Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => 'customer', 'namespace' => 'Customer'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
});
Route::get('/rodar-funcao', function(){
    getDocuments();
});

resources/views/admin/pages/admin/create.blade.php
@extends('admin.templates.default')

@section('title', 'Adicionar Administrador')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-1 text-dark">Adicionar Administrador</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <form action="{{route('admin.admin.store')}}" method="post">
                            {{csrf_field()}}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="name">Nome</label>
                                            <input type="text"
                                                class="form-control {{$errors->has('name') ? 'is-invalid' : ''}}"
                                                name="name" id="name">
                                            @if ($errors->has('name'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="email">E-mail</label>
                                            <input type="text"
                                                class="form-control {{$errors->has('email') ? 'is-invalid' : ''}}"
                                                name="email" id="email">
                                            @if ($errors->has('email'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="name">Senha</label>
                                            <input type="password"
                                                class="form-control {{$errors->has('name') ? 'is-invalid' : ''}}"
                                                name="password" id="password">
                                            @if ($errors->has('name'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="input-password_confirmation">Confirmação de Senha</label>
                                            <input type="password"
                                                class="form-control {{$errors->has('password') ? 'is-invalid' : ''}}"
                                                value="" name="password_confirmation" id="input-password_confirmation">
                                            @if ($errors->has('password'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('password') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button class="btn btn-primary-ieaga float-right">Adicionar</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->
                </div>

                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/admin/pages/admin/edit.blade.php
@extends('admin.templates.default')

@section('title', 'Editar Administrador')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-1 text-dark">Editar Administrador</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <form action="{{route('admin.admin.update', ['admin' => $admin])}}" method="post">
                            {{csrf_field()}}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="input-name">Nome</label>
                                            <input type="text" value="{{old('name', $admin->name)}}"
                                                class="form-control {{$errors->has('name') ? 'is-invalid' : ''}}"
                                                name="name" id="input-name">
                                            @if ($errors->has('name'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="input-email">E-mail</label>
                                            <input type="text"
                                                class="form-control {{$errors->has('email') ? 'is-invalid' : ''}}"
                                                value="{{old('email', $admin->email)}}" name="email"
                                                id="input-email">
                                            @if ($errors->has('email'))
                                            <span class="help-block">
                                                <small>
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </small>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button class="btn btn-primary-ieaga float-right">Atualizar</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->
                </div>
                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/admin/pages/admin/index.blade.php
@extends('admin.templates.default')

@section('title', 'Administradores')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Administradores</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <div class="float-right">
                        <button class="btn btn-success act-include"
                            data-url="{{route('admin.admin.create')}}">Adicionar</button>
                    </div>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Lista de Administradores</h3>
                            <div class="card-tools">
                                <?php

                                $paginate = $resources;
                                $link_limit = 7;
                                ?>

                                @if($paginate->lastPage() > 1)
                                <nav>
                                    <ul class="pagination pagination-sm">
                                        <li class="page-item {{ ($paginate->currentPage() == 1) ? ' disabled' : '' }}">
                                            <a class="page-link {{ $paginate->url(1)}}" href="#" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                        </li>
                                        @for($i = 1; $i <= $paginate->lastPage(); $i++)
                                            <?php
                                            $half_total_links = floor($link_limit / 2);
                                            $from = $paginate->currentPage() - $half_total_links;
                                            $to = $paginate->currentPage() + $half_total_links;
                                            if ($paginate->currentPage() < $half_total_links) {
                                            $to += $half_total_links - $paginate->currentPage();
                                            }
                                            if ($paginate->lastPage() - $paginate->currentPage() < $half_total_links) {
                                            $from -= $half_total_links - ($paginate->lastPage() - $paginate->currentPage()) - 1;
                                            }
                                            ?>
                                            <li
                                                class="page-item {{ ($paginate->currentPage() == $i) ? ' active' : '' }}">
                                                <a class="page-link" href="{{ $paginate->url($i)}}">{{ $i }}</a>
                                            </li>
                                            @endfor
                                            <li
                                                class="page-item {{ ($paginate->currentPage() == $paginate->lastPage()) ? ' disabled' : '' }}">
                                                <a class="page-link" href=" {{ $paginate->url($paginate->lastPage())}}"
                                                    aria-label="Next">
                                                    <span aria-hidden="true">&raquo;</span>
                                                    <span class="sr-only">Next</span>
                                                </a>
                                            </li>
                                    </ul>
                                </nav>
                                @endif
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-3">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>E-mail</th>
                                        <th>Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($resources as $resource)
                                    <tr>
                                        <td>{{$resource->name}}</td>
                                        <td>{{$resource->email}}</td>
                                        <td class="text-center align-middle py-0">
                                            <div class="btn-group btn-group-sm">
                                                <a href="{{route('admin.admin.edit', ['admin' => $resource])}}"
                                                    class="btn btn-primary-ieaga">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <button onclick="deleteItem(this, 1)"
                                                    data-href="{{route('admin.admin.delete', ['admin' => $resource])}}"
                                                    class="btn btn-danger act-delete">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan=3>Nenhum usuário cadastrado</td>
                                    </tr>
                                    @endforelse

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>

                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection