routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect( route('login') );
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/store', 'AdminController@store')->name('store');
        Route::get('/edit/{admin}', 'AdminController@edit')->name('edit');
        Route::get('/folder/change/{admin}/{folder}', 'AdminController@change')->name('change');
        Route::post('/update/{admin}', 'AdminController@update')->name('update');
        Route::get('/delete/{admin}', 'AdminController@delete')->name('delete');
    });
    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/store', 'CustomerController@store')->name('store');
        Route::get('/edit/{customer}', 'CustomerController@edit')->name('edit');
        Route::get('/folder/change/{customer}/{folder}', 'CustomerController@change')->name('change');
        Route::post('/update/{customer}', 'CustomerController@update')->name('update');
        Route::get('/delete/{customer}', 'CustomerController@delete')->name('delete');
        Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
            Route::post('/store/{customer}', 'CustomerCourseController@store')->name('store');
            Route::post('/update/{course}', 'CustomerCourseController@update')->name('update');
            Route::get('/delete/{course}', 'CustomerCourseController@delete')->name('delete');
        });
    });
    Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
        Route::get('/', 'CourseController@index')->name('index');
        Route::get('/create', 'CourseController@create')->name('create');
        Route::post('/store', 'CourseController@store')->name('store');
        Route::get('/edit/{course}', 'CourseController@edit')->name('edit');
        Route::get('/folder/change/{course}/{folder}', 'CourseController@change')->name('change');
        Route::post('/update/{course}', 'CourseController@update')->name('update');
        Route::get('/delete/{course}', 'CourseController@delete')->name('delete');
    });
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
    Route::group(['prefix' => 'folder', 'as' => 'folder.'], function () {
        Route::post('/store', 'FolderController@store')->name('store');
        Route::post('/update/{folder}', 'FolderController@update')->name('update');
        Route::get('/delete/{folder}', 'FolderController@delete')->name('delete');
    });
    Route::group(['prefix' => 'video', 'as' => 'video.'], function () {
        Route::post('/store', 'VideoController@store')->name('store');
        Route::post('/update/{video}', 'VideoController@update')->name('update');
        Route::get('/delete/{video}', 'VideoController@delete')->name('delete');
    });
    Route::group(['prefix' => 'document', 'as' => 'document.'], function () {
        Route::post('/store', 'DocumentController@store')->name('store');
        Route::post('/update/{document}', 'DocumentController@update')->name('update');
        Route::get('/change/{document}', 'DocumentController@change')->name('change');
        Route::get('/delete/{document}', 'DocumentController@delete')->name('delete');
    });
});

Route::group(['prefix' => 'customer'], function () {
    Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'CustomerAuth\LoginController@login');
    Route::get('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'CustomerAuth\RegisterController@register');

    Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => 'customer', 'namespace' => 'Customer'], function () {
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::post('account', 'AccountController@update')->name('account.update');
    Route::group(['prefix' => 'conteudo', 'as' => 'content.'], function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/show/{folder}', 'ContentController@show')->name('show');
    });
});
Route::get('/rodar-funcao', function(){
    getDocuments();
});

resources/views/admin/includes/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="https://imaxinformatica.com.br/">IEAGA. </a></strong>
    TODOS OS DIREITOS RESERVADOS.
    <div class="float-right d-none d-sm-inline-block">
        <b>Versão</b> 1.0.0
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('adminlte/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{asset('adminlte/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('adminlte/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('adminlte/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('adminlte/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('adminlte/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('adminlte/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('adminlte/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- bs-custom-file-input -->
<script src="{{asset('adminlte/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- Toastr -->
<script src="{{asset('adminlte/plugins/toastr/toastr.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.js')}}"></script>

<script type="text/javascript">

$('.btn-delete').on('click', function(e) {
    e.preventDefault();
    $('#confirmationModal .modal-title').html('Confirmação');
    $('#confirmationModal .modal-body p').html('Tem certeza que deseja realizar esta ação?');
    let href = $(this).attr('href');
    $('#confirmationModal').modal('show').on('click', '#confirm', function() {
        window.location.href = href;
    });
});


$(function() {
    // Summernote
    $('.textarea').summernote()
});
$('.btn-edit-folder').on('click', function(e) {
    e.preventDefault();
    let folderId = $(this).data('id');
    $(`.input-folder-${folderId}`).removeClass('display-none');
    $(`.card-${folderId}`).addClass('display-none');

});
$('.btn-edit-document').on('click', function(e) {
    e.preventDefault();
    let documentId = $(this).data('id');
    let name = $(this).data('name');
    let url = "{{route('admin.document.update', ['document' => 'documentValue'])}}";
    url = url.replace('documentValue', documentId);
    $('#modalEditDocument form').attr('action', url);
    $('#modalEditDocument input[name=name]').val(name);
    $('#modalEditDocument').modal('show');

});

let btnInclude = document.querySelector('.act-include');
if (btnInclude) {
    btnInclude.onclick = () => window.location.href = btnInclude.dataset.url;
}


function deleteItem(element, redirect = 0) {
    let href = element.dataset.href
    $('#confirmationModal .modal-title').html('Confirmação');
    $('#confirmationModal .modal-body p').html('Tem certeza que deseja prosseguir?');

    $('#confirmationModal').modal('show').on('click', '#confirm', function() {
        if (redirect === 0) {
            axios.get(href)
                .then(response => {
                    renderTable(response.data);
                    $('#confirmationModal').modal('hide');
                    toastr.success("Dados removidos com sucesso");
                }).catch(error => {});
        } else {
            window.location.href = href;
        }
    });
}

function validateError(response) {
    const {
        data: {
            error
        },
        status
    } = response;

    if (status === 406) {
        for (item in error) {
            let elementError = document.querySelector(`input[name=${item}]`);
            elementError.classList.add('is-invalid');
            toastr.error(error[item]);
        }
    }
}
</script>

@if(session()->has('success'))
<script>
$(document).ready(function() {
    toastr.success("{{session('success')}}");
});
</script>
@endif
@if(session()->has('status'))
<script>
$(document).ready(function() {
    toastr.info("{{session('status')}}");
});
</script>
@endif

@if(session()->has('error'))
<script>
$(document).ready(function() {
    toastr.error("{{session('error')}}");
});
</script>
@endif
@if ($errors->any())
@foreach ($errors->all() as $error)
<script>
$(document).ready(function() {
    toastr.error("{{ $error }}");
});
</script>
@endforeach
@endif
<script type="text/javascript">
$(document).ready(function() {
    bsCustomFileInput.init();
});
</script>
@yield('scripts')

resources/views/admin/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{{config('app.name')}} | @yield('title')</title>

<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet"
    href="{{asset('adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/jqvmap/jqvmap.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/daterangepicker/daterangepicker.css')}}">
<!-- summernote -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/summernote/summernote-bs4.css')}}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- Toastr -->
<link rel="stylesheet" href="{{asset('adminlte/plugins/toastr/toastr.min.css')}}">
<link rel="stylesheet" href="{{asset('css/adminlte.css')}}">

resources/views/admin/includes/header.blade.php
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{{url('/')}}"><img src="{{ asset('images/logo.png')}}" style="width:100px;" alt="Ieaga" /></a>
            </li>
        </ul>

        <!-- SEARCH FORM -->

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item">
                <a class="nav-link" href="{{url('admin/logout')}}">
                    <i class="fa fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </nav>

resources/views/admin/includes/mask.blade.php
<script src="https://unpkg.com/imask"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>

<script type="text/javascript">
function maskPhone() {
    let element = document.getElementsByClassName('input-phone');

    var maskOptions = {
        mask: '(00) 00000-0000'
    };
    for (item of element) {
        IMask(item, maskOptions);
    }
}
function maskCpf() {
    let element = document.getElementsByClassName('input-cpf');

    var maskOptions = {
        mask: '000.000.000-00'
    };
    for (item of element) {
        IMask(item, maskOptions);
    }
}

function maskMoney(element) {
    $(element).maskMoney({
        thousands: '.',
        decimal: ',',
        allowZero: true,
        symbolStay: true
    });
}
function maskDate() {
    let element = document.getElementsByClassName('input-date');

    var maskOptions = {
        mask: '00/00/0000'
    };
    for (item of element) {
        IMask(item, maskOptions);
    }
}
maskDate();
</script>

resources/views/admin/includes/modals.blade.php
<!--Exclusão-->
<div class="modal fade" id="confirmationModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="confirm">Confirmar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<!--/.Exclusão-->

@yield('modals')

resources/views/admin/includes/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-ieaga elevation-4">
    <!-- Brand Logo -->
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="#" class="d-block">{{Auth::guard('admin')->user()->name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview">
                    <a href="{{route('admin.content.index')}}"
                        class="nav-link {{request()->is('admin/conteudo*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Conteúdo</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{{route('admin.customer.index')}}"
                        class="nav-link {{request()->is('admin/customer*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Usuários</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{{route('admin.course.index')}}"
                        class="nav-link {{request()->is('admin/course*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-book"></i>
                        <p>Cursos</p>
                    </a>
                </li>
                @if(auth()->guard('admin')->user()->id < 5)
                <li class="nav-item has-treeview">
                    <a href="{{route('admin.admin.index')}}"
                        class="nav-link {{request()->is('admin/admin*') ? 'active' : ''}}">
                        <i class="fas fa-user-shield nav-icon "></i>
                        <p>Administradores</p>
                    </a>
                </li>
                @endif
                <li class="nav-item has-treeview">
                    <a href="{{route('admin.account.edit')}}"
                        class="nav-link {{request()->is('admin/account*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>Minha Conta</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{{url('admin/logout')}}"
                        class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>